### PR TITLE
Add option to not minimize to tray

### PR DESCRIPTION
**Pull request by mikkelkaas**

### CODE REVIEW

**Comment by VorlonCD** [comment]
Thanks!  What is the reason you wouldnt want to always minimize to tray?

**Comment by ipeterski** [comment]
heh.. guilt myself.. some times i do not realize it is still open and i open a new instance.. and at times can have 2 or 3 open at once, its not a 'bug fix' per say more of a 'quality of life-fix' for those who are forgetful. :)

*Great amazing work btw!!

**Comment by mikkelkaas** [comment]
Because it's nice to have the ability to choose.
And I'm running an emulated version af Windows, where minimize to tray doesn't work

**Comment by VorlonCD** [comment]
@mikkelkaas -  Ok, great.  I hadn't thought of that.  I think I made too many updates since your pull request.   Can you pull my latest and make the changes again.   I'll commit it as soon as you do.

@ipeterski - There should be an error showing up in the status bar and log if you open more than one copy.   Should I make this be a dialog that pops up as reminder?

**Comment by VorlonCD** [comment]
@mikkelkaas - FYI I implemented this in the latest version, just didnt pull from here because there would have been too many conflicts to deal with.   Thanks!

**Pull request closed without merging**
